apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: deny-etc-passwd
spec:
  selector:
    matchLabels:
      app: wisecow
  file:
    matchPaths:
      - path: /etc/passwd
        action: Block           


